### PR TITLE
Update api version

### PR DESCRIPTION
**Pull request by egeucak**
Updated buildpack version to the latest. I realize you have not been very active on github for the past few months but it will be great if we can merge this @fagiani

### CODE REVIEW

**Review by vishaljohn — APPROVED** [review]

**Review by WillGibson — APPROVED** [review]

**Comment by egeucak** [comment]
knock knock knock

**Review by AndresSando — APPROVED** [review]

**Comment by fagianijunior** [comment]
Hi man,

Unfortunately @fagiani is no longer with us, I will take over his repositories, those that I have access to.

I will accept you PR.

**Comment by egeucak** [comment]
I am sorry I had no idea. My condolences

**Comment by fagianijunior** [comment]
Hi @egeukac,

Thank you so much for your Pull Request! I appreciate the time and effort you put into contributing to the project.
I wanted to inform you that I have successfully gained access to my late cousin's account and will be providing support for it moving forward.
Additionally, the image fagiani/apt has been updated to version 0.2.6.

Please feel free to reach out if you have any questions or need further assistance.

Best regards,
Carlos Fagiani Junior

**Comment by GN-Bruno-Preti** [comment]
@fagianijunior, I'm really sorry for your loss.

Guys, this change broke our build and I'm not an expert on this. Do you have any suggestions on how to fix this?

> "PACK": ERROR: failed to build: validating buildpacks: buildpack 'fagiani/apt@0.2.6' (Buildpack API 0.10) is incompatible with lifecycle '0.16.5' (Buildpack API(s) 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)

**Comment by egeucak** [comment]
> @fagianijunior, I'm really sorry for your loss.
> 
> Guys, this change broke our build and I'm not an expert on this. Do you have any suggestions on how to fix this?
> 
> > "PACK": ERROR: failed to build: validating buildpacks: buildpack 'fagiani/apt@0.2.6' (Buildpack API 0.10) is incompatible with lifecycle '0.16.5' (Buildpack API(s) 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)

it has been quite a while since i have worked on a buildpacks project, and i didn't retest it after the update but as an easy solution you can downgrade back to `fagiani/apt@0.2.5`. but i would recommend you to update your lifecycle image. you might find it in your builder.toml if you have one

**Comment by GN-Bruno-Preti** [comment]
> > @fagianijunior, I'm really sorry for your loss.
> > Guys, this change broke our build and I'm not an expert on this. Do you have any suggestions on how to fix this?
> > > "PACK": ERROR: failed to build: validating buildpacks: buildpack 'fagiani/apt@0.2.6' (Buildpack API 0.10) is incompatible with lifecycle '0.16.5' (Buildpack API(s) 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
> 
> it has been quite a while since i have worked on a buildpacks project, and i didn't retest it after the update but as an easy solution you can downgrade back to `fagiani/apt@0.2.5`. but i would recommend you to update your lifecycle image. you might find it in your builder.toml if you have one

Thank you, @egeucak.

Downgrading was the short term solution that we ended up implementing and it worked, although we will try your other suggestion as soon as we're able to so we can avoid future issues.

Regards,
Bruno.

**Pull request merged**
